spring.application.name=stores

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/store
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379

server.port=8900